---

- name: check, for a valid system
  ansible.builtin.assert:
    msg: "this role works only with ArchLinux or Artix Linux"
    quiet: true
    that:
      - ansible_distribution | lower in [ "archlinux", "artix linux" ]

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. artixlinux
        - "{{ ansible_distribution | lower | replace(' ', '') }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: merge pacman config configuration between defaults and custom
  ansible.builtin.set_fact:
    pacman_config: "{{ pacman_defaults_config | combine(pacman_config, recursive=True) }}"
    pacman_repositories: "{{ pacman_defaults_repositories | combine(pacman_repositories, recursive=True) }}"
    pacman_mirrors: "{{ pacman_defaults_mirrors | combine(pacman_mirrors, recursive=True) }}"
    pacman_options: "{{ pacman_defaults_options | combine(pacman_options, recursive=True) }}"

...
